debug: false

server:
  port: 8080

spring:
  #DataSource
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update



